#!/usr/bin/env bash

# Is writing the theme to a random file in .cache a good idea? Probably not. Does it work well enough? Sure does
if [[ "$1" == "dark" ]]; then
    echo "dark" >  ~/.cache/theme
    exit 0
fi

if [[ "$1" == "light" ]]; then
    echo "light" >  ~/.cache/theme
    exit 0
fi

if [[ "$1" == "check" ]]; then
    theme=$(cat ~/.cache/theme 2> /dev/null)
    if [[ -n "$theme" ]]; then
        echo "$theme"
    else
        echo "dark"
    fi
    exit 0
fi

echo "Either provide the theme you want to switch to (dark/light), or do theme check to check the current theme"
exit 1
