#!/usr/bin/env bash

WORKSPACES_FILE="$HOME/.local/scripts/workspaces"
workspaces=$(cat $WORKSPACES_FILE)

function indicate_existing_sessions {
    local IFS=$'\n'    
    local lines=( $workspaces )
    for (( i=0; i<${#lines[@]}; i++ )); do
        session_name=$(echo "${lines[i]}" |  cut -d ' ' -f 1 | xargs)
        if tmux has -t=$session_name &> /dev/null; then
            lines[i]="${lines[i]} (exists)"
        fi
    done
    workspaces="${lines[@]#\$'\n'}"
}

create_session() {
    name=$(echo "$1" |  cut -d' ' -f 1 | xargs)
    path=$(echo "$1" | cut -d " " -f 2 | sed -n 's/.*(\(.*\)).*/\1/p')
    template=$(echo "$1" | sed -n 's/.*\[\(.*\)\].*/\1/p')

    if [[ -n "$template" ]]; then
        "create_${template}" "$name" "$path"
    else
        eval "tmux new-session -d -s $name -c $path"
    fi
}

create_dev() {
    local path="$2"
    eval "tmux new-session -ds $1 -c $path"
    eval "tmux splitw -h -t $1:1.1 -c $path"
    eval "tmux selectl -t $1:1.1 main-vertical"
}


if [[ $# -ge 1 ]]; then
    if [[ "$1" != "new" ]] || [[ $# -lt 2 ]]; then
        echo "usage: tmux-session-manager new [path] -t=[template]"
        exit 1
    fi

    
    path=$(realpath "$2" | sed "s+$HOME+~+g")

    template=$(echo "$3" | cut -d'=' -f 2 | xargs)
    entry="$(basename $path) ($path)"

    if [[ -n "$template" ]]; then 
        entry+=" [$template]"
    fi

    if ! grep -Fxq "$entry" $WORKSPACES_FILE; then
        echo "$entry" >> $WORKSPACES_FILE
    fi
    exit 0
fi

indicate_existing_sessions

# I use the ansi flag because maybe I'll color the workspace lines sometime
selected=$(echo "$workspaces" | fzf-tmux -p --ansi)

if [[ -z "$selected" ]]; then
    exit 0
fi


selected_session_name=$(echo "$selected" |  cut -d' ' -f 1 | xargs)

if ! tmux has -t=$selected_session_name &> /dev/null; then
    create_session "$selected"
fi

if ! { [[ $TERM == 'tmux'* ]] && [[ -n "$TMUX" ]] }; then
    tmux attach-session -t "$selected_session_name";
else
    tmux switch-client -t "$selected_session_name";
fi
