#!/usr/bin/env bash

picked_session=$(tmux ls | fzf-tmux -p | cut -d: -f 1 | xargs)

if [[ "$picked_session" == "" ]]; then
    ! { [[ $TERM == 'screen'* ]] && [[ -n "$TMUX" ]] } && echo "No session picked"
    exit 0
fi

if ! { [[ $TERM == 'screen'* ]] && [[ -n "$TMUX" ]] }; then
    tmux attach-session -t "$picked_session";
else
    tmux switch-client -t "$picked_session";
fi
