#!/usr/bin/env bash

# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

waylock_command="waylock -init-color 0x191724 -fail-color 0xeb6f92 -input-color 0x6e6a86 -submit-color 0x908caa"

riverctl map normal Super+Shift Return spawn wezterm

riverctl map normal Super Q close

riverctl map normal Super+Shift E exit

riverctl map normal Super E spawn "$waylock_command"

riverctl map normal Super D spawn fuzzel

riverctl map normal Super N focus-view next
riverctl map normal Super P focus-view previous

riverctl map normal Super+Shift N swap next
riverctl map normal Super+Shift P swap previous

riverctl map normal Super H focus-view left
riverctl map normal Super J focus-view down
riverctl map normal Super K focus-view up
riverctl map normal Super L focus-view right

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

riverctl map normal Super Return zoom

riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

riverctl map normal Super+Shift S spawn 'grim -g "$(slurp)" - | wl-copy'

riverctl map normal Super S spawn "systemctl suspend"

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
    riverctl map normal Super+Control $i toggle-focused-tags $tags
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super Space toggle-float
riverctl map normal Super F toggle-fullscreen

# riverctl declare-mode passthrough
# riverctl map normal Super F11 enter-mode passthrough
# riverctl map passthrough Super F11 enter-mode normal

for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

riverctl focus-follows-cursor normal

riverctl background-color 0x191724
riverctl border-color-focused 0xeb6f92
riverctl border-color-unfocused 0x6e6a86

riverctl set-repeat 30 300

riverctl rule-add ssd

riverctl input "pointer-1133-16514-Logitech_MX_Master_3" scroll-factor 2

riverctl keyboard-layout pl

# swaybg -i /home/chupson/wallpapers/rose-pine/moon.jpg -m fill &
swww-daemon &
swww img /home/chupson/wallpapers/thtaida1fk0b1.jpg -t none

# swayidle -w \
#          before-sleep 'swaylock -f -C ~/.local/share/themes/rose-pine/swaylock/rose-pine --clock --indicator' &
swayidle -w \
         before-sleep "$waylock_command" &

# Layout generator

# riverctl map normal Super H send-layout-cmd rivercarro "main-ratio -0.05"
# riverctl map normal Super L send-layout-cmd rivercarro "main-ratio +0.05"
#
# riverctl map normal Super+Shift H send-layout-cmd rivercarro "main-count +1"
# riverctl map normal Super+Shift L send-layout-cmd rivercarro "main-count -1"

riverctl map normal Super Up    send-layout-cmd rivercarro "main-location top"
riverctl map normal Super Right send-layout-cmd rivercarro "main-location right"
riverctl map normal Super Down  send-layout-cmd rivercarro "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivercarro "main-location left"

riverctl map normal Super T send-layout-cmd wideriver "--layout-toggle"

riverctl default-layout wideriver
# rivercarro -inner-gaps 6 -outer-gaps 8 &
wideriver \
    --layout                       left        \
    --layout-alt                   monocle     \
    --stack                        dwindle     \
    --count-master                 1           \
    --ratio-master                 0.60        \
    --no-smart-gaps                            \
    --inner-gaps                   6           \
    --outer-gaps                   8           \
    --border-width                 2           \
    --border-color-focused         "0xeb6f92"  \
    --border-color-focused-monocle "0xeb6f92"  \
    --border-color-unfocused       "0x6e6a86"  \
    --log-threshold                info        \
   > "/tmp/wideriver.${XDG_VTNR}.${USER}.log" 2>&1 &



mako &
waybar &
gammastep-indicator &
mullvad-vpn &
nm-applet &
blueman-applet &

kanshi &
